version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    hostname: localhost
    build: FakeTwitter # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forewarding
      - "433:433"
    links:
      - express
    depends_on:
      - express

  express: #name of the second service
    build: FakeTwitterServer # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service
    depends_on:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017" # specify port forewarding